### ISSUE TITLE
Install problems

### ISSUE THREAD

**Issue by munin-m** [YunoHost-Apps/incus_ynh#2]
### Describe the bug

Hello,

I've install the app via the web admin and via console with reboot and uninstall in between. The app just doesn't work, I doesn't show up in the userboard. When I go on it using the "application" menu in the admin panl of Yunohost, the page doesn't charge under the app title.  

### Context

- Hardware: x86 base local server
- YunoHost version: 11.2.11.2
- I have access to my server: Through SSH | through the webadmin.
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: No
- Using, or trying to install package version/branch: Normal package

### Steps to reproduce

I don't know the process is just installing the app via the yunohost webmin or the shell via command "sudo yunohost app install incus"

### Expected behavior

Something to work

### Logs

https://paste.yunohost.org/raw/ahagigokok

Here is how the shows int the webmin of yunohost:

![image](https://github.com/YunoHost-Apps/incus_ynh/assets/155631176/1c46ef7d-f219-4aed-8326-4e3603ffab7b)

Thanks for your help

**Comment by Salamandar** [comment]
Hi,
Incus is not a web app. It's a containerization technology. As such, there is no frontend so that's why it does not show up in the user dashboard.
As for the empty webadmin page… that's weird, we will check it out.
